По данным опроса, 75% работников ресторанов утверждают, что испытывают на работе существенный стресс, оказывающий негативное влияние на их личную жизнь. Крупная ресторанная сеть опрашивает 100 своих работников, чтобы выяснить, отличается ли уровень стресса работников в их ресторанах от среднего. 67 из 100 работников отметили высокий уровень стресса.

Посчитайте достигаемый уровень значимости, округлите ответ до четырёх знаков после десятичной точки.

In [65]:
nab, ozh = 67, 75
nab1, ozh1 = 100-nab, 100-ozh

In [66]:
x2 = (nab-ozh)**2/ozh + (nab1-ozh1)**2/ozh1
df = 1 #колличество степеней свободы

In [67]:
from scipy.stats import chi2

In [68]:
chi2.sf(x2, 1)

0.064671687502364045

In [11]:
nab, ozh = 22, 75
nab1, ozh1 = 50-nab, 100-ozh

In [63]:
x2 = (nab-ozh)**2/ozh + (nab1-ozh1)**2/ozh1
chi2.sf(x2, 1)

7.7847883047360148e-10

In [22]:
import pandas as pd
import numpy as np
from scipy.stats import binned_statistic_2d

In [23]:
sosny = pd.read_csv('pines.txt', sep='\t')

In [24]:
sosny.head()

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [26]:
sosny.min()[0]

0.0

In [39]:
X = sosny['sn'].values
Y = sosny['we'].values

In [40]:
bin_x = np.linspace(sosny.min()[0], sosny.max()[0], 6)
bin_y = np.linspace(sosny.min()[1], sosny.max()[1], 6)

In [42]:
S = binned_statistic_2d(X, Y, None, statistic  = 'count', bins=[bin_x,bin_y])

In [44]:
S.statistic

array([[ 18.,  26.,  29.,  25.,  20.],
       [ 14.,  12.,  22.,  34.,  25.],
       [ 12.,  24.,  15.,  50.,  37.],
       [  8.,  19.,  31.,  50.,   7.],
       [  7.,   8.,  37.,  27.,  27.]])

In [46]:
sosny.shape[0]/25

23.36

In [53]:
S.statistic.reshape(25,)

array([ 18.,  26.,  29.,  25.,  20.,  14.,  12.,  22.,  34.,  25.,  12.,
        24.,  15.,  50.,  37.,   8.,  19.,  31.,  50.,   7.,   7.,   8.,
        37.,  27.,  27.])

In [55]:
from scipy import stats

In [56]:
Z = stats.chisquare(S.statistic.reshape(25,), ddof = 0)

In [58]:
Z[0]

150.58904109589042

In [59]:
stats.chisquare(24, 0)

/home/lenart/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:4567: RuntimeWarning: divide by zero encountered in true_divide
  terms = (f_obs - f_exp)**2 / f_exp


Power_divergenceResult(statistic=inf, pvalue=nan)

In [70]:
chi2.sf(Z, 24)

array([  2.57466977e-20,   1.00000000e+00])